#ifndef WONDERCOIN_CHAINPARAMSSEEDS_H
#define WONDERCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the wondercoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x2f,0xfb,0x2d,0x1f}, 8888},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x2d,0x94,0xa5,0xef}, 8888}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // WONDERCOIN_CHAINPARAMSSEEDS_H
